apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}-ingress
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
  {{- if .Values.ingress.singleHost.enabled }}
  - host: {{ .Values.ingress.hosts.ui }}
    http:
      paths:
      - backend:
          service:
            name:  {{ template "ui.fullname" . }}
            port:
              number: 80
        path: {{ .Values.ingress.singleHost.uiPath }}
        pathType: Prefix
      - backend:
          service:
            name:  {{ template "api.fullname" . }}
            port:
              number: 80
        path: {{ .Values.ingress.singleHost.apiPath }}
        pathType: Prefix
      - backend:
          service:
            name:  {{ template "store.fullname" . }}
            port:
              number: 80
        path: {{ .Values.ingress.singleHost.storePath }}
        pathType: Prefix
  {{- else }}
  - host: {{ .Values.ingress.hosts.ui }}
    http:
      paths:
      - backend:
          service:
            name:  {{ template "ui.fullname" . }}
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: {{ .Values.ingress.hosts.api }}
    http:
      paths:
      - backend:
          service:
            name:  {{ template "api.fullname" . }}
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: {{ .Values.ingress.hosts.store }}
    http:
      paths:
      - backend:
          service:
            name:  {{ template "store.fullname" . }}
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: {{ .Values.ingress.hosts.queue }}
    http:
      paths:
      - backend:
          service:
            name:  {{ template "queue.fullname" . }}
            port:
              number: 80
        path: /
        pathType: Prefix
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  {{- if .Values.ingress.singleHost.enabled }}
  - hosts:
    - {{ .Values.ingress.hosts.ui }}
    secretName: screwdriver-ui-tls
  {{- else }}
  - hosts:
    - {{ .Values.ingress.hosts.ui }}
    secretName: screwdriver-ui-tls
  - hosts:
    - {{ .Values.ingress.hosts.api }}
    secretName: screwdriver-api-tls
  - hosts:
    - {{ .Values.ingress.hosts.store }}
    secretName: screwdriver-store-tls
  {{- end }}
{{- end }}
